//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloraSoft {
    
    public partial class OCEBatchTree {
        protected System.Web.UI.WebControls.DropDownList ZoneList;
        protected System.Web.UI.WebControls.DropDownList BranchList;
        protected System.Web.UI.WebControls.DropDownList ClearingTypeList;
        protected System.Web.UI.WebControls.TreeView StatusTreeView1;
    }
}
