//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloraSoft.modules {
    
    public partial class BankSettlement {
        protected System.Web.UI.WebControls.ImageButton PrintBtn;
        protected System.Web.UI.HtmlControls.HtmlGenericControl SettlementViewDiv;
        protected System.Web.UI.WebControls.GridView SettlementGrid;
        protected System.Web.UI.WebControls.Label LblTotal;
        protected System.Web.UI.WebControls.Label iOCE;
        protected System.Web.UI.WebControls.Label OCE;
        protected System.Web.UI.WebControls.Label iICE;
        protected System.Web.UI.WebControls.Label ICE;
        protected System.Web.UI.WebControls.Label iORE;
        protected System.Web.UI.WebControls.Label ORE;
        protected System.Web.UI.WebControls.Label iIRE;
        protected System.Web.UI.WebControls.Label IRE;
    }
}
