//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloraSoft.modules {
    
    public partial class OCEBranchStatus {
        protected System.Web.UI.HtmlControls.HtmlGenericControl OCEBranchViewDiv;
        protected System.Web.UI.WebControls.GridView BranchGrid;
        protected System.Web.UI.WebControls.Label LblTotal;
        protected System.Web.UI.WebControls.Label Scanman;
        protected System.Web.UI.WebControls.Label Maker;
        protected System.Web.UI.WebControls.Label Checker;
        protected System.Web.UI.HtmlControls.HtmlAnchor Admin;
        protected System.Web.UI.WebControls.Label PBM;
        protected System.Web.UI.WebControls.Label Total;
        protected System.Web.UI.WebControls.Label IQA;
        protected System.Web.UI.WebControls.Label IRE;
    }
}
